### ISSUE TITLE
[Bug]: <style> element in _document.js cause a 500 server error in SSR pages

### ISSUE THREAD

**Issue by sa3dany** [netlify/netlify-plugin-nextjs#1047]
### Summary

Putting a `<style>` element in `_document.js` cause 500 server errors on any SSR page when deployed to Netlify.

```jsx
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <style>
            {`
              #__next {
                background-color: lightblue;
              }
            `}
          </style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

### Steps to reproduce

Test site: [https://angry-goldberg-e973a1.netlify.app/](https://angry-goldberg-e973a1.netlify.app/)

- Based on `create-next-app@latest`
- Modified `index.js` to be SSR
- Added the default `_document.js` with a `<style>` tag in the head

I could not reproduce locally either with `next dev` or `next start`.

### A link to a reproduction repository

https://github.com/sa3dany/style-in-custom-document

### Plugin version

4.1.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Windows

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
publish = ".next"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```js
module.exports = {
  reactStrictMode: true,
}
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
1:03:12 AM: Build ready to start
1:03:14 AM: build-image version: a6bb34428a07e7de82f4df5dfe1843fbde91f670 (focal)
1:03:14 AM: build-image tag: v4.5.1
1:03:14 AM: buildbot version: 77cc2674bad27d648057c8495db565f7d4c11e75
1:03:14 AM: Fetching cached dependencies
1:03:14 AM: Failed to fetch cache, continuing with build
1:03:14 AM: Starting to prepare the repo for build
1:03:14 AM: No cached dependencies found. Cloning fresh repo
1:03:14 AM: git clone https://github.com/sa3dany/style-in-custom-document
1:03:15 AM: Preparing Git Reference refs/heads/main
1:03:15 AM: Parsing package.json dependencies
1:03:16 AM: Starting build script
1:03:16 AM: Installing dependencies
1:03:16 AM: Python version set to 2.7
1:03:17 AM: v16.13.1 is already installed.
1:03:17 AM: Now using node v16.13.1 (npm v8.1.2)
1:03:17 AM: Started restoring cached build plugins
1:03:17 AM: Finished restoring cached build plugins
1:03:17 AM: Attempting ruby version 2.7.2, read from environment
1:03:19 AM: Using ruby version 2.7.2
1:03:19 AM: Using PHP version 8.0
1:03:19 AM: Started restoring cached yarn cache
1:03:19 AM: Finished restoring cached yarn cache
1:03:20 AM: No yarn workspaces detected
1:03:20 AM: Started restoring cached node modules
1:03:20 AM: Finished restoring cached node modules
1:03:20 AM: Installing NPM modules using Yarn version 1.22.10
1:03:21 AM: yarn install v1.22.10
1:03:21 AM: [1/4] Resolving packages...
1:03:21 AM: [2/4] Fetching packages...
1:03:39 AM: info @next/swc-android-arm64@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-android-arm64@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-android-arm64@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info @next/swc-darwin-arm64@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-darwin-arm64@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-darwin-arm64@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info @next/swc-darwin-x64@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-darwin-x64@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-linux-arm-gnueabihf@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info "@next/swc-linux-arm-gnueabihf@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-linux-arm64-gnu@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info "@next/swc-linux-arm64-gnu@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-linux-arm64-musl@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info "@next/swc-linux-arm64-musl@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-win32-arm64-msvc@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-win32-arm64-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-win32-arm64-msvc@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info @next/swc-win32-ia32-msvc@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-win32-ia32-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info @next/swc-win32-ia32-msvc@12.0.7: The CPU architecture "x64" is incompatible with this module.
1:03:39 AM: info @next/swc-win32-x64-msvc@12.0.7: The platform "linux" is incompatible with this module.
1:03:39 AM: info "@next/swc-win32-x64-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
1:03:39 AM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
1:03:39 AM: [3/4] Linking dependencies...
1:03:39 AM: warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
1:03:39 AM: warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
1:03:44 AM: [4/4] Building fresh packages...
1:03:48 AM: Done in 27.08s.
1:03:48 AM: NPM modules installed using Yarn
1:03:48 AM: Started restoring cached go cache
1:03:48 AM: Finished restoring cached go cache
1:03:48 AM: go version go1.16.5 linux/amd64
1:03:48 AM: go version go1.16.5 linux/amd64
1:03:48 AM: Installing missing commands
1:03:48 AM: Verify run directory
1:03:50 AM: ​
1:03:50 AM: ────────────────────────────────────────────────────────────────
1:03:50 AM:   Netlify Build                                                 
1:03:50 AM: ────────────────────────────────────────────────────────────────
1:03:50 AM: ​
1:03:50 AM: ❯ Version
1:03:50 AM:   @netlify/build 26.0.0
1:03:50 AM: ​
1:03:50 AM: ❯ Flags
1:03:50 AM:   baseRelDir: true
1:03:50 AM:   buildId: 61c0fda0fab722709950ce52
1:03:50 AM:   deployId: 61c0fda0fab722709950ce54
1:03:50 AM: ​
1:03:50 AM: ❯ Current directory
1:03:50 AM:   /opt/build/repo
1:03:50 AM: ​
1:03:50 AM: ❯ Config file
1:03:50 AM:   /opt/build/repo/netlify.toml
1:03:50 AM: ​
1:03:50 AM: ❯ Context
1:03:50 AM:   production
1:03:50 AM: ​
1:03:50 AM: ❯ Loading plugins
1:03:50 AM:    - @netlify/plugin-nextjs@4.1.0 from netlify.toml and package.json
1:03:52 AM: ​
1:03:52 AM: ────────────────────────────────────────────────────────────────
1:03:52 AM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
1:03:52 AM: ────────────────────────────────────────────────────────────────
1:03:52 AM: ​
1:03:52 AM: No Next.js cache to restore.
1:03:52 AM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
1:03:52 AM: ​
1:03:52 AM: (@netlify/plugin-nextjs onPreBuild completed in 62ms)
1:03:52 AM: ​
1:03:52 AM: ────────────────────────────────────────────────────────────────
1:03:52 AM:   2. Build command from Netlify app                             
1:03:52 AM: ────────────────────────────────────────────────────────────────
1:03:52 AM: ​
1:03:52 AM: $ yarn build
1:03:52 AM: yarn run v1.22.10
1:03:52 AM: $ next build
1:03:53 AM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
1:03:53 AM: info  - Checking validity of types...
1:03:56 AM: info  - Creating an optimized production build...
1:04:06 AM: info  - Compiled successfully
1:04:06 AM: info  - Collecting page data...
1:04:10 AM: info  - Generating static pages (0/2)
1:04:10 AM: info  - Generating static pages (2/2)
1:04:10 AM: info  - Finalizing page optimization...
1:04:10 AM: Page                                       Size     First Load JS
1:04:10 AM: ┌ λ /                                      5.03 kB        76.5 kB
1:04:10 AM: ├   └ css/b282b959608f58d4.css             718 B
1:04:10 AM: ├   /_app                                  0 B            71.5 kB
1:04:10 AM: ├ ○ /404                                   194 B          71.7 kB
1:04:10 AM: └ λ /api/hello                             0 B            71.5 kB
1:04:10 AM: + First Load JS shared by all              71.5 kB
1:04:10 AM:   ├ chunks/framework-6e4ba497ae0c8a3f.js   42 kB
1:04:10 AM:   ├ chunks/main-7e73d61bce33e887.js        28.2 kB
1:04:10 AM:   ├ chunks/pages/_app-9cd1d19dd7237c4c.js  493 B
1:04:10 AM:   ├ chunks/webpack-514908bffb652963.js     770 B
1:04:10 AM:   └ css/2974ebc8daa97b04.css               209 B
1:04:10 AM: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
1:04:10 AM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
1:04:10 AM: Done in 18.02s.
1:04:10 AM: ​
1:04:10 AM: (build.command completed in 18.2s)
1:04:10 AM: ​
1:04:10 AM: ────────────────────────────────────────────────────────────────
1:04:10 AM:   3. @netlify/plugin-nextjs (onBuild event)                     
1:04:10 AM: ────────────────────────────────────────────────────────────────
1:04:10 AM: ​
1:04:10 AM: Moving static page files to serve from CDN...
1:04:10 AM: Moved 0 files
1:04:10 AM: Netlify configuration property "redirects" value changed to [
1:04:10 AM:   { from: '/_next/static/*', to: '/static/:splat', status: 200 },
1:04:10 AM:   {
1:04:10 AM:     from: '/_next/image*',
1:04:10 AM:     query: { url: ':url', w: ':width', q: ':quality' },
1:04:10 AM:     to: '/_ipx/w_:width,q_:quality/:url',
1:04:10 AM:     status: 301
1:04:10 AM:   },
1:04:10 AM:   { from: '/_ipx/*', to: '/.netlify/builders/_ipx', status: 200 },
1:04:10 AM:   { from: '/cache/*', to: '/404.html', status: 404, force: true },
1:04:10 AM:   { from: '/server/*', to: '/404.html', status: 404, force: true },
1:04:10 AM:   { from: '/serverless/*', to: '/404.html', status: 404, force: true },
1:04:10 AM:   { from: '/traces', to: '/404.html', status: 404, force: true },
1:04:10 AM:   {
1:04:10 AM:     from: '/routes-manifest.json',
1:04:10 AM:     to: '/404.html',
1:04:10 AM:     status: 404,
1:04:10 AM:     force: true
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/build-manifest.json',
1:04:10 AM:     to: '/404.html',
1:04:10 AM:     status: 404,
1:04:10 AM:     force: true
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/prerender-manifest.json',
1:04:10 AM:     to: '/404.html',
1:04:10 AM:     status: 404,
1:04:10 AM:     force: true
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/react-loadable-manifest.json',
1:04:10 AM:     to: '/404.html',
1:04:10 AM:     status: 404,
1:04:10 AM:     force: true
1:04:10 AM:   },
1:04:10 AM:   { from: '/BUILD_ID', to: '/404.html', status: 404, force: true },
1:04:10 AM:   {
1:04:10 AM:     from: '/api',
1:04:10 AM:     to: '/.netlify/functions/___netlify-handler',
1:04:10 AM:     status: 200
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/api/*',
1:04:10 AM:     to: '/.netlify/functions/___netlify-handler',
1:04:10 AM:     status: 200
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/favicon.ico',
1:04:10 AM:     to: '/favicon.ico',
1:04:10 AM:     conditions: { Cookie: [Array] },
1:04:10 AM:     status: 200
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/vercel.svg',
1:04:10 AM:     to: '/vercel.svg',
1:04:10 AM:     conditions: { Cookie: [Array] },
1:04:10 AM:     status: 200
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/*',
1:04:10 AM:     to: '/.netlify/functions/___netlify-handler',
1:04:10 AM:     status: 200,
1:04:10 AM:     conditions: { Cookie: [Array] },
1:04:10 AM:     force: true
1:04:10 AM:   },
1:04:10 AM:   {
1:04:10 AM:     from: '/*',
1:04:10 AM:     to: '/.netlify/functions/___netlify-handler',
1:04:10 AM:     status: 200
1:04:10 AM:   }
1:04:10 AM: ].
1:04:10 AM: ​
1:04:10 AM: (@netlify/plugin-nextjs onBuild completed in 78ms)
1:04:10 AM: ​
1:04:10 AM: ────────────────────────────────────────────────────────────────
1:04:10 AM:   4. Functions bundling                                         
1:04:10 AM: ────────────────────────────────────────────────────────────────
1:04:10 AM: ​
1:04:10 AM: Packaging Functions from .netlify/functions-internal directory:
1:04:10 AM:  - ___netlify-handler/___netlify-handler.js
1:04:10 AM:  - ___netlify-odb-handler/___netlify-odb-handler.js
1:04:10 AM:  - _ipx/_ipx.js
1:04:10 AM: ​
1:04:39 AM: ​
1:04:39 AM: (Functions bundling completed in 28.2s)
1:04:39 AM: ​
1:04:39 AM: ────────────────────────────────────────────────────────────────
1:04:39 AM:   5. @netlify/plugin-nextjs (onPostBuild event)                 
1:04:39 AM: ────────────────────────────────────────────────────────────────
1:04:39 AM: ​
1:04:39 AM: Next.js cache saved.
1:04:39 AM: ​
1:04:39 AM: (@netlify/plugin-nextjs onPostBuild completed in 89ms)
1:04:39 AM: ​
1:04:39 AM: ────────────────────────────────────────────────────────────────
1:04:39 AM:   6. Deploy site                                                
1:04:39 AM: ────────────────────────────────────────────────────────────────
1:04:39 AM: ​
1:04:39 AM: Starting to deploy site from '.next'
1:04:39 AM: Creating deploy tree 
1:04:39 AM: Creating deploy upload records
1:04:39 AM: 16 new files to upload
1:04:39 AM: 3 new functions to upload
1:04:47 AM: Site deploy was successfully initiated
1:04:47 AM: ​
1:04:47 AM: (Deploy site completed in 8.1s)
1:04:47 AM: ​
1:04:47 AM: ────────────────────────────────────────────────────────────────
1:04:47 AM: Starting post processing
1:04:47 AM:   Netlify Build Complete                                        
1:04:47 AM: ────────────────────────────────────────────────────────────────
1:04:47 AM: ​
1:04:47 AM: (Netlify Build completed in 56.9s)
1:04:47 AM: Post processing - HTML
1:04:47 AM: Post processing - header rules
1:04:47 AM: Post processing - redirect rules
1:04:47 AM: Post processing done
1:04:47 AM: Caching artifacts
1:04:47 AM: Started saving node modules
1:04:47 AM: Finished saving node modules
1:04:47 AM: Started saving build plugins
1:04:47 AM: Finished saving build plugins
1:04:47 AM: Started saving yarn cache
1:04:48 AM: Site is live ✨
1:04:51 AM: Finished saving yarn cache
1:04:51 AM: Started saving pip cache
1:04:51 AM: Finished saving pip cache
1:04:51 AM: Started saving emacs cask dependencies
1:04:51 AM: Finished saving emacs cask dependencies
1:04:51 AM: Started saving maven dependencies
1:04:51 AM: Finished saving maven dependencies
1:04:51 AM: Started saving boot dependencies
1:04:51 AM: Finished saving boot dependencies
1:04:51 AM: Started saving rust rustup cache
1:04:51 AM: Finished saving rust rustup cache
1:04:51 AM: Started saving go dependencies
1:04:51 AM: Finished saving go dependencies
1:04:53 AM: Build script success
1:06:13 AM: Finished processing build request in 2m59.51786636s
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
1:04:57 AM: 6793cd92 ERROR  TypeError: Cannot assign to read only property 'children' of object '#<Object>'
    at /var/task/.next/server/chunks/859.js:728:37
    at /var/task/node_modules/react/cjs/react.development.js:1067:17
    at mapIntoArray (/var/task/node_modules/react/cjs/react.development.js:964:23)
    at mapIntoArray (/var/task/node_modules/react/cjs/react.development.js:1004:23)
    at Object.mapChildren [as map] (/var/task/node_modules/react/cjs/react.development.js:1066:3)
    at Head.makeStylesheetInert (/var/task/.next/server/chunks/859.js:717:40)
    at Head.render (/var/task/.next/server/chunks/859.js:755:29)
    at processChild (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3450:18)
    at resolve (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
#build-manifest
{
  "polyfillFiles": [
    "static/chunks/polyfills-5cd94c89d3acac5f.js"
  ],
  "devFiles": [],
  "ampDevFiles": [],
  "lowPriorityFiles": [
    "static/zgI8F0gQ0WwCV2odJMeLk/_buildManifest.js",
    "static/zgI8F0gQ0WwCV2odJMeLk/_ssgManifest.js",
    "static/zgI8F0gQ0WwCV2odJMeLk/_middlewareManifest.js"
  ],
  "pages": {
    "/": [
      "static/chunks/webpack-514908bffb652963.js",
      "static/chunks/framework-6e4ba497ae0c8a3f.js",
      "static/chunks/main-7e73d61bce33e887.js",
      "static/css/b282b959608f58d4.css",
      "static/chunks/pages/index-2b9a33ff0018b5f5.js"
    ],
    "/_app": [
      "static/chunks/webpack-514908bffb652963.js",
      "static/chunks/framework-6e4ba497ae0c8a3f.js",
      "static/chunks/main-7e73d61bce33e887.js",
      "static/css/2974ebc8daa97b04.css",
      "static/chunks/pages/_app-9cd1d19dd7237c4c.js"
    ],
    "/_error": [
      "static/chunks/webpack-514908bffb652963.js",
      "static/chunks/framework-6e4ba497ae0c8a3f.js",
      "static/chunks/main-7e73d61bce33e887.js",
      "static/chunks/pages/_error-2280fa386d040b66.js"
    ]
  },
  "ampFirstPages": []
}


# export-manifest
{"version":1,"hasExportPathMap":false,"exportTrailingSlash":false,"isNextImageImported":true}


# images-manifest
{"version":1,"images":{"deviceSizes":[640,750,828,1080,1200,1920,2048,3840],"imageSizes":[16,32,48,64,96,128,256,384],"path":"/_next/image","loader":"default","domains":[],"disableStaticImages":false,"minimumCacheTTL":60,"formats":["image/webp"],"sizes":[640,750,828,1080,1200,1920,2048,3840,16,32,48,64,96,128,256,384]}}


# prerender-manifest
{"version":3,"routes":{},"dynamicRoutes":{},"preview":{"previewModeId":"f3983c54121fbeda554862c9acf5ad7a","previewModeSigningKey":"6d0300d77bcddc7dada4f6afce90cbb368f6a3157aa1d86614352c8a979a05a9","previewModeEncryptionKey":"ac49f48b85fc9d42d7688ac085b958be595e65c60266428c1f0211988d2fb1a7"},"notFoundRoutes":[]}


# react-loadable-manifest
{}


# required-server-files
{"version":1,"config":{"env":{},"webpack":null,"webpackDevMiddleware":null,"eslint":{"ignoreDuringBuilds":false},"typescript":{"ignoreBuildErrors":false,"tsconfigPath":"tsconfig.json"},"distDir":".next","cleanDistDir":true,"assetPrefix":"","configOrigin":"next.config.js","useFileSystemPublicRoutes":true,"generateEtags":true,"pageExtensions":["tsx","ts","jsx","js"],"target":"server","poweredByHeader":true,"compress":false,"analyticsId":"","images":{"deviceSizes":[640,750,828,1080,1200,1920,2048,3840],"imageSizes":[16,32,48,64,96,128,256,384],"path":"/_next/image","loader":"default","domains":[],"disableStaticImages":false,"minimumCacheTTL":60,"formats":["image/webp"]},"devIndicators":{"buildActivity":true,"buildActivityPosition":"bottom-right"},"onDemandEntries":{"maxInactiveAge":15000,"pagesBufferLength":2},"amp":{"canonicalBase":""},"basePath":"","sassOptions":{},"trailingSlash":false,"i18n":null,"productionBrowserSourceMaps":false,"optimizeFonts":true,"excludeDefaultMomentLocales":true,"serverRuntimeConfig":{},"publicRuntimeConfig":{},"reactStrictMode":true,"httpAgentOptions":{"keepAlive":true},"outputFileTracing":true,"staticPageGenerationTimeout":60,"swcMinify":false,"experimental":{"cpus":7,"sharedPool":true,"plugins":false,"profiling":false,"isrFlushToDisk":true,"workerThreads":false,"pageEnv":false,"optimizeImages":false,"optimizeCss":false,"scrollRestoration":false,"externalDir":false,"reactRoot":false,"disableOptimizedLoading":false,"gzipSize":true,"swcFileReading":true,"craCompat":false,"esmExternals":true,"isrMemoryCacheSize":52428800,"concurrentFeatures":false,"serverComponents":false,"fullySpecified":false,"outputFileTracingRoot":"","outputStandalone":false},"configFileName":"next.config.js"},"appDir":"C:\\Users\\sa3dany\\wh\\repos\\style-in-custom-document","files":[".next\\routes-manifest.json",".next\\server\\pages-manifest.json",".next\\build-manifest.json",".next\\prerender-manifest.json",".next\\server\\middleware-manifest.json",".next\\react-loadable-manifest.json",".next\\server\\font-manifest.json",".next\\BUILD_ID"],"ignore":["node_modules\\next\\dist\\compiled\\@ampproject\\toolbox-optimizer\\**\\*"]}


# routes-manifest
{"version":3,"pages404":true,"basePath":"","redirects":[{"source":"/:path+/","destination":"/:path+","internal":true,"statusCode":308,"regex":"^(?:/((?:[^/]+?)(?:/(?:[^/]+?))*))/$"}],"headers":[],"dynamicRoutes":[],"staticRoutes":[{"page":"/","regex":"^/(?:/)?$","routeKeys":{},"namedRegex":"^/(?:/)?$"}],"dataRoutes":[{"page":"/","dataRouteRegex":"^/_next/data/zgI8F0gQ0WwCV2odJMeLk/index.json$"}],"rewrites":[]} 
```

</details>

**Comment by ascorbic** [comment]
Thanks for the report! It seems that React was using the development runtime, which was causing this error. If you upgrade the plugin to 4.1.1 it should fix this.
