### ISSUE TITLE
Issue with existing netlify/function failing Next.js builds

### ISSUE THREAD

**Issue by nico-frozencoffee** [netlify/netlify-plugin-nextjs#275]
I'm building a personal website that I intend to use next.js with netlify and I'm recently getting the following error from the plugin. This happened when I started renaming/refactoring some files around. ~~This issue effectively bricks my site. As I see no way to just delete the auto generated functions.~~

Update: The issue seems to be that dynamic pages like [slug].tsx and [...slug].tsx become the same named function file. I removed a file I called [...slug].tsx and now just use [slug].tsx and the build passed.

Considering I'm unblocked I'm ok with closing the issue, but would like to perhaps get some eyes on some documentation as to why this works or in this case doesn't work.

```
Plugin "@netlify/plugin-nextjs" internal error

Error: 'netlify/functions/next_slug/next_slug.js' already exists

In "onBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
at mayCopyFile (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
at onFile (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
at getStats (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
at startCopy (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
at handleFilterAndCopy (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
at copySync (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
at setupNetlifyFunctionForPage (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/helpers/setupNetlifyFunctionForPage.js:24:3)
at /opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/pages/getStaticPropsWithFallback/setup.js:21:11
at asyncForEach (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/helpers/asyncForEach.js:3:11)
at async setup (/opt/build/repo/node_modules/@netlify/plugin-nextjs/src/lib/pages/getStaticPropsWithFallback/setup.js:17:3)
```

[Git repo](https://github.com/nico-frozencoffee/omc)
[Build](https://app.netlify.com/sites/omc-dev/deploys/609732f92e0bb100074c0e47)

**To Reproduce**
Create 2 files

pages/[slug].tsx
pages/[...slug].tsx

A same named netlify function file will be created for both files. I'm unsure if this is bad practice or not.

**Versions**
 - Next: 10.2.0
 - @netlify/plugin-nextjs: 3.2.2
 - Node: 16.1.0

**Comment by nico-frozencoffee** [comment]
I'm still new to Next.js so I was following a tutorial that created both a [slug].tsx and [...slug].tsx file. After some time, I'm convinced that the [...slug].tsx file is in fact not needed because I noticed in local development that the [...slug].tsx getStaticProps never gets called but [slug].tsx does. I've opted to just delete [...slug].tsx and chalk this up to a rough learning experience.
