### ISSUE TITLE
Error: Cannot find module 'execa'

### ISSUE THREAD

**Issue by tolchai** [netlify/netlify-plugin-nextjs#287]
Hi,

starting today i get the following plugin error during the build process:

```
Plugin "@netlify/plugin-nextjs" internal error

Error: Cannot find module 'execa'
Require stack:

/opt/build/repo/web/.netlify/plugins/node_modules/next-on-netlify/index.js

/opt/build/repo/web/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js

/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/logic.js

/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/load.js

/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js

In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
at Function.Module._load (internal/modules/cjs/loader.js:840:27)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (/opt/build/repo/web/.netlify/plugins/node_modules/next-on-netlify/index.js:4:15)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)

Error properties:
{ code: 'MODULE_NOT_FOUND' }
```

**Versions**
- Next.js: 10.0.3
- plugin: 1.1.4

I've tried to revert to previous content which built without an issue, but the problem still persists.

**Comment by tolchai** [comment]
Ok, adding exaca within the dependencies of the project solved the issue.
