### ISSUE TITLE
next/amp throwing error

### ISSUE THREAD

**Issue by samiahmedsiddiqui** [netlify/netlify-plugin-nextjs#383]
**Describe the bug**

I have site that contains amp pages and it works fine locally but as soon as it deploys to Netlify it start throwing error. Error occurs when I add the following config in page.

```js
export const config = { amp: true }
```

**Error**

```js
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot find module 'next/dist/compiled/source-map'\nRequire stack:\n- /var/task/src/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js\n- /var/task/src/functions/next_slug_amp/nextPage/pages/[slug]/amp.js\n- /var/task/src/functions/next_slug_amp/nextPage/index.js\n- /var/task/src/functions/next_slug_amp/renderNextPage.js\n- /var/task/src/functions/next_slug_amp/next_slug_amp.js\n- /var/task/next_slug_amp.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","trace":["Runtime.UnhandledPromiseRejection: Error: Cannot find module 'next/dist/compiled/source-map'","Require stack:","- /var/task/src/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js","- /var/task/src/functions/next_slug_amp/nextPage/pages/[slug]/amp.js","- /var/task/src/functions/next_slug_amp/nextPage/index.js","- /var/task/src/functions/next_slug_amp/renderNextPage.js","- /var/task/src/functions/next_slug_amp/next_slug_amp.js","- /var/task/next_slug_amp.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:314:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```

**Expected behavior**
It should render the AMP page as document here:
- https://nextjs.org/docs/api-reference/next/amp
- https://www.netlify.com/blog/2020/12/19/enabling-amp-in-your-next.js-projects/

**Versions**
- Next.js: `10.2.3`

**If you're using file-based installation**
- netlify.toml:
  ```yml
  [build]
    functions = "functions"
    # Default build command.
    command = "npm run build"
  ```

**Comment by lindsaylevine** [comment]
@samiahmedsiddiqui hey! thanks for reporting this to us :) can you let us know what error you're seeing? it's also best to give us a repo that reproduces the error you're seeing, if you can!

**Comment by samiahmedsiddiqui** [comment]
@lesliecdubs I have added the Error in the description. Sorry I can give you repo link as it is private. Only config line is throwing the error, as soon as I remove that line error gets fixed but definitely page is no longer the AMP.
