### ISSUE TITLE
Can't find "nextjs" dependency in NPM v7 Monorepo

### ISSUE THREAD

**Issue by revmischa** [netlify/netlify-plugin-nextjs#537]
I'm using a NPM v7 monorepo.  The setup is based on https://github.com/jetbridge/typescript-cdk-template
My netlify config looks something like:
```toml
[build]
  # install npm 7 and build from top level
  command = "cd ../.. && npm run build:ci:frontend"

  # where NextJS lives
  base = "packages/ats-frontend"
  publish = "packages/ats-frontend/build"

  # use node 16 (comes with NPM 7)
  environment = { NODE_VERSION = "16.4.2", NPM_FLAGS = "--legacy-peer-deps" }
```

In `packages/frontend/package.json` I have a dependency on `"next": "^11.0.1"`

`build:ci:frontend` is not relevant because the plugin failure is happening before that:
```
12:03:48 PM: Now using node v16.4.2 (npm v7.18.1)
12:03:48 PM: Started restoring cached build plugins
12:03:48 PM: Finished restoring cached build plugins
12:03:49 PM: Attempting ruby version 2.7.2, read from environment
12:03:50 PM: Using ruby version 2.7.2
12:03:50 PM: Using PHP version 7.4
12:03:50 PM: Started restoring cached node modules
12:03:50 PM: Finished restoring cached node modules
12:03:50 PM: Started restoring cached go cache
12:03:50 PM: Finished restoring cached go cache
12:03:50 PM: go version go1.14.4 linux/amd64
12:03:50 PM: go version go1.14.4 linux/amd64
12:03:50 PM: Installing missing commands
12:03:50 PM: Verify run directory
12:03:51 PM: ​
12:03:51 PM: ────────────────────────────────────────────────────────────────
12:03:51 PM:   Netlify Build                                                 
12:03:51 PM: ────────────────────────────────────────────────────────────────
12:03:51 PM: ​
12:03:51 PM: ❯ Version
12:03:51 PM:   @netlify/build 15.11.5
12:03:51 PM: ​
12:03:51 PM: ❯ Flags
12:03:51 PM:   deployId: 60f53fdd014e340007ba6dfc
12:03:51 PM: ​
12:03:51 PM: ❯ Current directory
12:03:51 PM:   /opt/build/repo/packages/ats-frontend
12:03:51 PM: ​
12:03:51 PM: ❯ Config file
12:03:51 PM:   /opt/build/repo/netlify.toml
12:03:51 PM: ​
12:03:51 PM: ❯ Context
12:03:51 PM:   deploy-preview
12:03:51 PM: ​
12:03:51 PM: ❯ Installing plugins
12:03:51 PM:    - @netlify/plugin-nextjs@3.7.1
12:03:53 PM: ​
12:03:53 PM: ❯ Loading plugins
12:03:53 PM:    - @netlify/plugin-nextjs@3.7.1 from netlify.toml
12:03:54 PM: ​
12:03:54 PM: ────────────────────────────────────────────────────────────────
12:03:54 PM:   1. onPreBuild command from @netlify/plugin-nextjs             
12:03:54 PM: ────────────────────────────────────────────────────────────────
12:03:54 PM: ​
12:03:54 PM: ​
12:03:54 PM: ────────────────────────────────────────────────────────────────
12:03:54 PM:   Plugin "@netlify/plugin-nextjs" failed                        
12:03:54 PM: ────────────────────────────────────────────────────────────────
12:03:54 PM: ​
12:03:54 PM:   Error message
12:03:54 PM:   Error: This site does not seem to be using Next.js. Please run "npm install next" in the repository.
12:03:54 PM:   If you are using a monorepo, please see the docs on configuring your site: https://ntl.fyi/next-monorepos
12:03:54 PM: ​
12:03:54 PM:   Plugin details
12:03:54 PM:   Package:        @netlify/plugin-nextjs
12:03:54 PM:   Version:        3.7.1
12:03:54 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
12:03:54 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
12:03:54 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
12:03:54 PM: ​
12:03:54 PM:   Error location
12:03:54 PM:   In "onPreBuild" event in "@netlify/plugin-nextjs" from netlify.toml
12:03:54 PM:       at validateNextUsage (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/helpers/validateNextUsage.js:15:12)
12:03:54 PM:       at onPreBuild (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:23:5)
12:03:54 PM: ​
12:03:54 PM:   Resolved config
12:03:54 PM:   build:
12:03:54 PM:     base: /opt/build/repo/packages/ats-frontend
12:03:54 PM:     command: cd ../.. && npm run build:ci:frontend
12:03:54 PM:     commandOrigin: config
12:03:54 PM:     environment:
12:03:54 PM:       - REVIEW_ID
12:03:54 PM:       - NODE_VERSION
12:03:54 PM:       - NPM_FLAGS
12:03:54 PM:     publish: /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:03:54 PM:     publishOrigin: config
12:03:54 PM:   plugins:
12:03:54 PM:     - inputs: {}
12:03:54 PM:       origin: config
12:03:54 PM:       package: '@netlify/plugin-nextjs'
```

Netlify should detect that next is provided by the package in my monorepo but *sometimes* it does not. It seems to be somewhat random as far as I can tell if it detects that next is present or not. 
I tried adding next to the top-level `dependencies`, and then the build completes but I get this error instead:
```
12:12:54 PM: ────────────────────────────────────────────────────────────────
12:12:54 PM:   3. onBuild command from @netlify/plugin-nextjs                
12:12:54 PM: ────────────────────────────────────────────────────────────────
12:12:54 PM: ​
12:12:54 PM: Detected Next.js site. Copying files...
12:12:54 PM: ** Running Next on Netlify package **
12:12:54 PM: 🚀 Next on Netlify 🚀
12:12:54 PM: 🌍️ Copying public folder to /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:12:54 PM: 💼 Copying static NextJS assets to /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:12:54 PM: 💫 Setting up API endpoints as Netlify Functions in /opt/build/repo/packages/ats-frontend/netlify/functions
12:12:54 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in /opt/build/repo/packages/ats-frontend/netlify/functions
12:12:54 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in /opt/build/repo/packages/ats-frontend/netlify/functions
12:12:54 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:12:54 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in /opt/build/repo/packages/ats-frontend/netlify/functions
12:12:54 PM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in /opt/build/repo/packages/ats-frontend/netlify/functions
12:12:54 PM: 🔥 Copying pre-rendered pages without props to /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:12:54 PM: Building 4 pages
12:12:54 PM: ​
12:12:54 PM: ────────────────────────────────────────────────────────────────
12:12:54 PM:   Plugin "@netlify/plugin-nextjs" internal error                
12:12:54 PM: ────────────────────────────────────────────────────────────────
12:12:54 PM: ​
12:12:54 PM:   Error message
12:12:54 PM:   Error: ENOENT: no such file or directory, stat '/opt/build/repo/packages/ats-frontend/node_modules/@netlify/plugin-nextjs/src/lib/templates/netlifyFunction.js'
12:12:54 PM: ​
12:12:54 PM:   Plugin details
12:12:54 PM:   Package:        @netlify/plugin-nextjs
12:12:54 PM:   Version:        3.7.1
12:12:54 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
12:12:54 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
12:12:54 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
12:12:54 PM: ​
12:12:54 PM:   Error location
12:12:54 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
12:12:54 PM:       at Object.statSync (node:fs:1526:3)
12:12:54 PM:       at Object.statSync (/opt/build/repo/packages/ats-frontend/node_modules/graceful-fs/polyfills.js:311:34)
12:12:54 PM:       at statSync (/opt/build/repo/packages/ats-frontend/node_modules/fs-extra/lib/util/stat.js:10:52)
12:12:54 PM:       at getStatsSync (/opt/build/repo/packages/ats-frontend/node_modules/fs-extra/lib/util/stat.js:24:19)
12:12:54 PM:       at Object.checkPathsSync (/opt/build/repo/packages/ats-frontend/node_modules/fs-extra/lib/util/stat.js:49:33)
12:12:54 PM:       at copySync (/opt/build/repo/packages/ats-frontend/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
12:12:54 PM:       at setupNetlifyFunctionForPage (/opt/build/repo/packages/ats-frontend/node_modules/@netlify/plugin-nextjs/src/lib/helpers/setupNetlifyFunctionForPage.js:25:3)
12:12:54 PM:       at processPage (/opt/build/repo/packages/ats-frontend/node_modules/@netlify/plugin-nextjs/src/lib/pages/worker.js:8:16)
12:12:54 PM:       at asyncWrapper (/opt/build/repo/packages/ats-frontend/node_modules/fastq/queue.js:213:12)
12:12:54 PM:       at push (/opt/build/repo/packages/ats-frontend/node_modules/fastq/queue.js:110:14)
12:12:54 PM: ​
12:12:54 PM:   Error properties
12:12:54 PM:   {
12:12:54 PM:     errno: -2,
12:12:54 PM:     syscall: 'stat',
12:12:54 PM:     code: 'ENOENT',
12:12:54 PM:     path: '/opt/build/repo/packages/ats-frontend/node_modules/@netlify/plugin-nextjs/src/lib/templates/netlifyFunction.js'
12:12:54 PM:   }
12:12:54 PM: ​
12:12:54 PM:   Resolved config
12:12:54 PM:   build:
12:12:54 PM:     base: /opt/build/repo/packages/ats-frontend
12:12:54 PM:     command: cd ../.. && npm run build:ci:frontend
12:12:54 PM:     commandOrigin: config
12:12:54 PM:     environment:
12:12:54 PM:       - REVIEW_ID
12:12:54 PM:       - NODE_VERSION
12:12:54 PM:       - NPM_FLAGS
12:12:54 PM:     publish: /opt/build/repo/packages/ats-frontend/packages/ats-frontend/build
12:12:54 PM:     publishOrigin: config
12:12:54 PM:   plugins:
12:12:54 PM:     - inputs: {}
12:12:54 PM:       origin: config
12:12:54 PM:       package: '@netlify/plugin-nextjs'
```

And I don't want it in the top level anyway because my backend packages don't need next.

**Comment by revmischa** [comment]
Also I noticed that it fails to parse the npm `-w` flag for specifying which workspace to run my commands in:
`12:26:47 PM: There was an error parsing your build command: [parsePackageScript] missing script with name: -w
12:26:47 PM: The build command is "npm run build:ci:frontend" and the available npm scripts are: "postinstall",  .... "prettier", "lint", "test", "clean"`

**Comment by leobenkel** [comment]
I am facing similar issues. After wiping out all cache, I can't get your error message anymore but I am getting https://github.com/netlify/netlify-plugin-nextjs/issues/539 instead.

**Comment by lindsaylevine** [comment]
@revmischa @leobenkel hello! sorry you're running into this!

question: is this a brand new site you're setting up on netlify or is it an older site that worked on a previous version of the plugin? if it's an older site that previously worked, maybe you can unblock yourself by installing the plugin at a previous version (see https://github.com/netlify/netlify-plugin-nextjs/releases).

i'll defer to my teammate who's done all the recent monorepo work (@ascorbic) but in the meantime, can you provide an extension of the template you shared that exactly repros the error you're reporting? that would be most helpful. @leobenkel a repro from you would be great as well!

**Comment by revmischa** [comment]
Yes my setup looks roughly like this https://github.com/revmischa/netlify-nextjs-repro
I get various errors that seemly appear at random. Some clear themselves up if I clear cache and rebuild.

Sometimes it says I don't have `next` as a dependency, sometimes it can't find the serverless function output.

I'm not sure if I should be building from my project top level (most of the node_modules are in the top level) or in the frontend project (where the next project is but without most of the node_modules because they've been hoisted to the top level).

Right now I am staring at this error:
```ts
{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token '.'","trace":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token '.'","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}
```
Which is odd because it runs fine locally (even using `netlify dev`).

**Comment by leobenkel** [comment]
I am not sure what I changed but it ended up working at the end. Thank you for your answer.

**Comment by ascorbic** [comment]
Hi @revmischa. Sorry you're having these problems. Based on the config in [your repro](https://github.com/revmischa/netlify-nextjs-repro) I think it's related to youyr build command and base directory. Can you try changing your config to something like this:

```toml
[build]

  command = "npm run build:ci:frontend"
  base = "."
  publish = "packages/frontend/out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

```
There's more info at https://ntl.fyi/next-monorepos
Rather than manually install NPM 7 in your build command, you can set the env var `NPM_VERSION`. You also don't need to install @netlify/plugin-nextjs in your build command: it will be installed automatically if it's not in your dependencies.
Let me know how you get on!

**Comment by revmischa** [comment]
Thanks yeah that basically worked!
```toml
[build]
  # install npm 7 and build from top level
  command = "npm run build:ci:frontend"

  # where NextJS lives
  base = "."
  publish = "packages/frontend/build"

  # use node 16 (comes with NPM 7)
  environment = { NODE_VERSION = "16.4.2", NPM_FLAGS = "--legacy-peer-deps" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by ascorbic** [comment]
That's great! I'll close it in that case. Let us know if you have any more questions.
