### ISSUE TITLE
Error: next-i18next was unable to find a user config - build ok

### ISSUE THREAD

**Issue by tgmarinho** [netlify/netlify-plugin-nextjs#595]
Build on Netlify is ok, but I'm getting this error when I try to access the link of the project:

```
Error: next-i18next was unable to find a user config"
```

```
// 20210810141354
// https://censured-url.netlify.app/

{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: next-i18next was unable to find a user config",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: next-i18next was unable to find a user config",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}

```

Build Log:

```
1:42:40 PM: Build ready to start
1:42:41 PM: build-image version: 653805ca4a64301556e56dc4b321ef8fc20cbb7c
1:42:41 PM: build-image tag: v3.8.2
1:42:41 PM: buildbot version: 2b0f40952f9d7ae48d3a1e6f3cb5615369d40788
1:42:42 PM: Fetching cached dependencies
1:42:42 PM: Starting to download cache of 403.5MB
1:42:47 PM: Finished downloading cache in 4.975012923s
1:42:47 PM: Starting to extract cache
1:43:02 PM: Finished extracting cache in 15.115060552s
1:43:02 PM: Finished fetching cache in 20.192442139s
1:43:02 PM: Starting to prepare the repo for build
1:43:03 PM: Preparing Git Reference refs/heads/fix/bundle-size
1:43:04 PM: Parsing package.json dependencies
1:43:05 PM: Starting build script
1:43:05 PM: Installing dependencies
1:43:05 PM: Python version set to 2.7
1:43:05 PM: Started restoring cached node version
1:43:08 PM: Finished restoring cached node version
1:43:09 PM: v14.17.3 is already installed.
1:43:10 PM: Now using node v14.17.3 (npm v6.14.13)
1:43:10 PM: Started restoring cached build plugins
1:43:10 PM: Finished restoring cached build plugins
1:43:10 PM: Attempting ruby version 2.7.1, read from environment
1:43:10 PM: Started restoring cached ruby version
1:43:10 PM: Finished restoring cached ruby version
1:43:12 PM: Using ruby version 2.7.1
1:43:13 PM: Using PHP version 5.6
1:43:13 PM: Started restoring cached yarn cache
1:43:20 PM: Finished restoring cached yarn cache
1:43:21 PM: No yarn workspaces detected
1:43:21 PM: Started restoring cached node modules
1:43:21 PM: Finished restoring cached node modules
1:43:21 PM: Installing NPM modules using Yarn version 1.22.4
1:43:22 PM: yarn install v1.22.4
1:43:22 PM: [1/4] Resolving packages...
1:43:22 PM: success Already up-to-date.
1:43:22 PM: $ husky install
1:43:22 PM: husky - Git hooks installed
1:43:22 PM: Done in 0.55s.
1:43:22 PM: NPM modules installed using Yarn
1:43:22 PM: Started restoring cached go cache
1:43:22 PM: Finished restoring cached go cache
1:43:22 PM: go version go1.14.4 linux/amd64
1:43:22 PM: go version go1.14.4 linux/amd64
1:43:22 PM: Installing missing commands
1:43:22 PM: Verify run directory
1:43:23 PM: ​
1:43:23 PM: ────────────────────────────────────────────────────────────────
1:43:23 PM:   Netlify Build                                                 
1:43:23 PM: ────────────────────────────────────────────────────────────────
1:43:23 PM: ​
1:43:23 PM: ❯ Version
1:43:23 PM:   @netlify/build 17.9.2
1:43:23 PM: ​
1:43:23 PM: ❯ Flags
1:43:23 PM:   baseRelDir: true
1:43:23 PM:   deployId: 6112ba906c15340007bea895
1:43:23 PM: ​
1:43:23 PM: ❯ Current directory
1:43:23 PM:   /opt/build/repo
1:43:23 PM: ​
1:43:23 PM: ❯ Config file
1:43:23 PM:   /opt/build/repo/netlify.toml
1:43:23 PM: ​
1:43:23 PM: ❯ Context
1:43:23 PM:   production
1:43:23 PM: ​
1:43:23 PM: ❯ Loading plugins
1:43:23 PM:    - @netlify/plugin-nextjs@3.8.0 from netlify.toml
1:43:24 PM: ​
1:43:24 PM: ────────────────────────────────────────────────────────────────
1:43:24 PM:   1. onPreBuild command from @netlify/plugin-nextjs             
1:43:24 PM: ────────────────────────────────────────────────────────────────
1:43:24 PM: ​
1:43:24 PM: Using Next.js 11.0.1
1:43:24 PM: info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
1:43:25 PM: Next.js cache restored.
1:43:25 PM: ​
1:43:25 PM: (@netlify/plugin-nextjs onPreBuild completed in 1.6s)
1:43:25 PM: ​
1:43:25 PM: ────────────────────────────────────────────────────────────────
1:43:25 PM:   2. build.command from netlify.toml                            
1:43:25 PM: ────────────────────────────────────────────────────────────────
1:43:25 PM: ​
1:43:25 PM: $ yarn build
1:43:25 PM: yarn run v1.22.4
1:43:26 PM: $ next build
1:43:27 PM: info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
1:43:27 PM: info  - Checking validity of types...
1:43:43 PM: info  - Creating an optimized production build...
1:45:54 PM: info  - Compiled successfully
1:45:54 PM: info  - Collecting page data...
1:46:07 PM: info  - Generating static pages (0/5)
1:46:15 PM: info  - Generating static pages (1/5)
1:46:15 PM: info  - Generating static pages (2/5)
1:46:16 PM: info  - Generating static pages (3/5)
1:46:16 PM: info  - Generating static pages (5/5)
1:46:16 PM: info  - Finalizing page optimization...
1:46:16 PM: Page                                                              Size     First Load JS
1:46:16 PM: ┌ λ /                                                             4.69 kB        1.53 MB
1:46:16 PM: ├   /_app                                                         0 B             1.5 MB
1:46:16 PM: ├ ○ /404                                                          1.02 kB         1.5 MB
1:46:16 PM: ├ λ /asset/[id]                                                   79 kB          1.62 MB
1:46:16 PM: ├ λ /auction/[id]                                                 2.18 kB        1.54 MB
1:46:16 PM: ├ λ /auctions                                                     4.74 kB        1.53 MB
1:46:16 PM: ├ λ /collection/[name]                                            1.81 kB        1.57 MB
1:46:16 PM: ├ λ /create                                                       15.8 kB        1.56 MB
1:46:16 PM: ├   └ css/35d7ff29d0e68c80cf85.css                                3.59 kB
1:46:16 PM: ├ λ /createdrop                                                   1.15 kB        1.54 MB
1:46:16 PM: ├ ● /customize                                                    991 B          1.54 MB
1:46:16 PM: ├ ● /customize/collection                                         1.07 kB        1.54 MB
1:46:16 PM: ├ λ /customize/collection/[colName]                               783 B          1.54 MB
1:46:16 PM: ├ λ /customize/collection/[colName]/schema                        1.12 kB        1.54 MB
1:46:16 PM: ├ λ /customize/collection/[colName]/schema/[schemaName]           983 B          1.57 MB
1:46:16 PM: ├ λ /customize/collection/[colName]/schema/[schemaName]/mint      1.66 kB        1.54 MB
1:46:16 PM: ├ λ /customize/collection/[colName]/schema/[schemaName]/template  1.53 kB        1.54 MB
1:46:16 PM: ├ λ /drop-edit/[id]                                               1.78 kB        1.54 MB
1:46:16 PM: ├ λ /drop/[id]                                                    7.31 kB        1.51 MB
1:46:16 PM: ├   └ css/9cd921426b443282625e.css                                1.21 kB
1:46:16 PM: ├ λ /marketplace                                                  7.63 kB        1.54 MB
1:46:16 PM: ├   └ css/475ca31934be1ae916e5.css                                3.69 kB
1:46:16 PM: ├ λ /profile/[id]                                                 5.81 kB        1.53 MB
1:46:16 PM: └ λ /ranking                                                      7.58 kB        1.51 MB
1:46:16 PM:     └ css/a3d0fdf5555f2ba25f19.css                                4.9 kB
1:46:16 PM: + First Load JS shared by all                                     1.5 MB
1:46:16 PM:   ├ chunks/framework.2f6124.js                                    42.4 kB
1:46:16 PM:   ├ chunks/main.2340b7.js                                         21.2 kB
1:46:16 PM:   ├ chunks/pages/_app.51c6e0.js                                   1.43 MB
1:46:16 PM:   ├ chunks/webpack.834817.js                                      2.05 kB
1:46:16 PM:   └ css/a64886491626b3d1f175.css                                  73.7 kB
1:46:16 PM: λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
1:46:16 PM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
1:46:16 PM: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
1:46:16 PM:    (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
1:46:16 PM: Done in 170.43s.
1:46:16 PM: ​
1:46:16 PM: (build.command completed in 2m 50.6s)
1:46:16 PM: ​
1:46:16 PM: ────────────────────────────────────────────────────────────────
1:46:16 PM:   3. onBuild command from @netlify/plugin-nextjs                
1:46:16 PM: ────────────────────────────────────────────────────────────────
1:46:16 PM: ​
1:46:16 PM: Detected Next.js site. Copying files...
1:46:16 PM: ** Running Next on Netlify package **
1:46:16 PM: 🚀 Next on Netlify 🚀
1:46:16 PM: 🌍️ Copying public folder to /opt/build/repo/out
1:46:16 PM: 💼 Copying static NextJS assets to /opt/build/repo/out
1:46:16 PM: 💫 Setting up API endpoints as Netlify Functions in /opt/build/repo/netlify/functions
1:46:16 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in /opt/build/repo/netlify/functions
1:46:16 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in /opt/build/repo/netlify/functions
1:46:16 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo/out
1:46:16 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in /opt/build/repo/netlify/functions
1:46:16 PM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in /opt/build/repo/netlify/functions
1:46:16 PM: 🔥 Copying pre-rendered pages without props to /opt/build/repo/out
1:46:16 PM: Building 27 pages
1:46:16 PM: 🔀 Setting up redirects
1:46:16 PM: 🔀 Setting up headers
1:46:16 PM: ✅ Success! All done!
1:46:16 PM: ​
1:46:16 PM: (@netlify/plugin-nextjs onBuild completed in 358ms)
1:46:16 PM: ​
1:46:16 PM: ────────────────────────────────────────────────────────────────
1:46:16 PM:   4. Functions bundling                                         
1:46:16 PM: ────────────────────────────────────────────────────────────────
1:46:16 PM: ​
1:46:17 PM: Packaging Functions from netlify/functions directory:
1:46:17 PM:  - next_404/next_404.js
1:46:17 PM:  - next_asset_id/next_asset_id.js
1:46:17 PM:  - next_auction_id/next_auction_id.js
1:46:17 PM:  - next_auctions/next_auctions.js
1:46:17 PM:  - next_collection_name/next_collection_name.js
1:46:17 PM:  - next_create/next_create.js
1:46:17 PM:  - next_createdrop/next_createdrop.js
1:46:17 PM:  - next_customize/next_customize.js
1:46:17 PM:  - next_customize_collection/next_customize_collection.js
1:46:17 PM:  - next_customize_collection_colName/next_customize_collection_colName.js
1:46:17 PM:  - next_customize_collection_colName_schema/next_customize_collection_colName_schema.js
1:46:17 PM:  - next_customize_collection_colName_schema_schemaName/next_customize_collection_colName_schema_schemaName.js
1:46:17 PM:  - next_customize_collection_colName_schema_schemaName_mint/next_customize_collection_colName_schema_schemaName_mint.js
1:46:17 PM:  - next_customize_collection_colName_schema_schemaName_template/next_customize_collection_colName_schema_schemaName_template.js
1:46:17 PM:  - next_drop_id/next_drop_id.js
1:46:17 PM:  - next_dropedit_id/next_dropedit_id.js
1:46:17 PM:  - next_image/next_image.js
1:46:17 PM:  - next_index/next_index.js
1:46:17 PM:  - next_marketplace/next_marketplace.js
1:46:17 PM:  - next_profile_id/next_profile_id.js
1:46:17 PM:  - next_ranking/next_ranking.js
1:46:17 PM: ​
1:51:12 PM: ​
1:51:12 PM: ❯ The following Node.js modules use dynamic expressions to include files:
1:51:12 PM:    - next-i18next
1:51:12 PM: ​
1:51:12 PM:   Because files included with dynamic expressions aren't bundled with your serverless functions by default,
  this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
1:51:12 PM:   modules as external in the [functions] section of your `netlify.toml` configuration file:
1:51:12 PM: ​
1:51:12 PM:   [functions]
1:51:12 PM:     external_node_modules = ["next-i18next"]
1:51:12 PM: ​
1:51:12 PM:   Visit https://ntl.fyi/dynamic-imports for more information.
1:51:12 PM: ​
1:51:12 PM: ​
1:51:12 PM: (Functions bundling completed in 4m 55.9s)
1:51:12 PM: ​
1:51:12 PM: ────────────────────────────────────────────────────────────────
1:51:12 PM:   5. onPostBuild command from @netlify/plugin-nextjs            
1:51:12 PM: ────────────────────────────────────────────────────────────────
1:51:12 PM: ​
1:51:13 PM: Next.js cache saved.
1:51:13 PM: ​
1:51:13 PM: (@netlify/plugin-nextjs onPostBuild completed in 595ms)
1:51:13 PM: ​
1:51:13 PM: ────────────────────────────────────────────────────────────────
1:51:13 PM:   6. Deploy site                                                
1:51:13 PM: ────────────────────────────────────────────────────────────────
1:51:13 PM: ​
1:51:13 PM: Starting to deploy site from 'out'
1:51:16 PM: Creating deploy tree 
1:51:16 PM: Creating deploy upload records
1:51:16 PM: 6 new files to upload
1:51:16 PM: 21 new functions to upload
1:51:32 PM: Site deploy was successfully initiated
1:51:32 PM: ​
1:51:32 PM: (Deploy site completed in 19s)
1:51:32 PM: Starting post processing
1:51:32 PM: ​
1:51:32 PM: ────────────────────────────────────────────────────────────────
1:51:32 PM:   Netlify Build Complete                                        
1:51:32 PM: ────────────────────────────────────────────────────────────────
1:51:32 PM: ​
1:51:32 PM: (Netlify Build completed in 8m 9s)
1:51:32 PM: Post processing - HTML
1:51:32 PM: Caching artifacts
1:51:32 PM: Started saving node modules
1:51:32 PM: Finished saving node modules
1:51:32 PM: Started saving build plugins
1:51:32 PM: Post processing - header rules
1:51:32 PM: Finished saving build plugins
1:51:32 PM: Started saving yarn cache
1:51:33 PM: Post processing - redirect rules
1:51:33 PM: Post processing done
1:51:33 PM: Site is live ✨
1:51:41 PM: Finished saving yarn cache
1:51:41 PM: Started saving pip cache
1:51:42 PM: Finished saving pip cache
1:51:42 PM: Started saving emacs cask dependencies
1:51:42 PM: Finished saving emacs cask dependencies
1:51:42 PM: Started saving maven dependencies
1:51:42 PM: Finished saving maven dependencies
1:51:42 PM: Started saving boot dependencies
1:51:42 PM: Finished saving boot dependencies
1:51:42 PM: Started saving rust rustup cache
1:51:42 PM: Finished saving rust rustup cache
1:51:42 PM: Started saving go dependencies
1:51:42 PM: Finished saving go dependencies
1:51:42 PM: Build script success
1:52:58 PM: Finished processing build request in 10m16.965824994s
```

next.config.js:
```
const withPlugins = require("next-compose-plugins");
const { withSentryConfig } = require("@sentry/nextjs");
const withAntdLess = require("next-plugin-antd-less");
const libtheme = require("./libtheme");
const { i18n } = require("./next-i18next.config");

const withBundleAnalyzer = require("@next/bundle-analyzer")({
	enabled: process.env.ANALYZE === "true",
});

const SentryWebpackPluginOptions = {
	dryRun: true,
	silent: true,
};

const nextConfig = {
	target: "experimental-serverless-trace",
	reactStrictMode: true,
	poweredByHeader: false,
	productionBrowserSourceMaps: false,
	reactStrictMode: true,
	poweredByHeader: false,
	images: {
		deviceSizes: [300, 640, 750, 828, 1080, 1200, 1920, 2048, 3840],
		imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
		domains: [ ... ],
	},
	eslint: {
		ignoreDuringBuilds: true,
	},
	i18n,
};

const plugins = [
	withBundleAnalyzer,
	[withAntdLess, { modifyVars: libtheme }],
	[
		withSentryConfig,
		{
			sentry: {
				disableServerWebpackPlugin: true,
				disableClientWebpackPlugin: true,
			},
			publicRuntimeConfig: {
				dns: process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN,
			},
			SentryWebpackPluginOptions,
		},
	],
];

module.exports = withPlugins([...plugins], nextConfig);

```

next-i18next.config.js
```
/* eslint-disable no-undef */
module.exports = {
	i18n: {
		defaultLocale: "en",
		locales: ["en"],
		ns: ["common"],
		defaultNS: "common",
	},
};

```

**Versions**
- Next.js:
- plugin (if installed at fixed version):
```
"next": "^11.0.1",
"next-compose-plugins": "^2.2.1",
"next-i18next": "^8.5.5",
```

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows] - MacOS
 - netlify/cli version: nops

**If you're using file-based installation**
- netlify.toml:
```
[build]
  command   = "yarn build"
  publish   = "out"

[[plugins]]
  package   = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
	external_node_modules = ["next", "@ampproject/toolbox-optimizer", "sharp"]

```

**Comment by tgmarinho** [comment]
oh… Even when I put, the line bellow at `netlify.toml` I get same errror:

```
1:51:12 PM:   [functions]
1:51:12 PM:     external_node_modules = ["next-i18next"]
```

**Comment by tgmarinho** [comment]
Maybe it is related with: https://github.com/netlify/netlify-plugin-nextjs/issues/223

**Comment by lindsaylevine** [comment]
@tgmarinho hey! i think it is definitely the same issue as #223. are you using `serverSideTranslations` as well as the user that posted 223? you might want to pass your config directly to that function (see my comment here https://github.com/netlify/netlify-plugin-nextjs/issues/223#issuecomment-832977548). you can also try to use the toml functions config `included_files` (see docs here https://docs.netlify.com/configure-builds/file-based-configuration/#functions) to make sure your next-i18next config is included. for ex:

```
[functions]

included_files = ["{/path/to/next-i18next-config}"]
```

if you cant figure it out with these suggestions, providing a repo that i could fiddle with myself would probably be our best bet for guaranteeing it works smoothly. let me know!

**Comment by tgmarinho** [comment]
Hey @lindsaylevine thank you, I tried this:

``` 
[build]
  command = "yarn build"
  publish   = "out"

[[plugins]]
  package   = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
	external_node_modules = ["next", "@ampproject/toolbox-optimizer", "sharp", "next-i18next"]
  included_files = ["public/locales/en/*.json", "/var/task/next-i18next.config.js"]
```

And I'm getting this error:

![image](https://user-images.githubusercontent.com/380327/131512193-3b475a72-0b99-47cc-89c0-0c2c8b866d2c.png)



The app is big, I don't know right now with some code is breaking the rules of the hooks, localhost is working and Heroku also, netlify not yet.

**Comment by lindsaylevine** [comment]
hey! remove `next` from `external_node_modules` and that should fix your issue. (i assume you added that per recommendation of build logs, and we're working to correct that now in the CLI)

**Comment by tgmarinho** [comment]
@lindsaylevine I removed this, keeping this way:

```
[build]
  command = "yarn build"
  publish   = "out"

[[plugins]]
  package   = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
	external_node_modules = ["@ampproject/toolbox-optimizer", "sharp", "next-i18next"]
  included_files = ["public/locales/en/*.json", "/var/task/next-i18next.config.js"]

```

But not work yet.

I'll remove `netlify/plugin-nextjs` just to update to 3.9.0.

```
[[plugins]]
  package   = "@netlify/plugin-nextjs"
```

**Comment by tgmarinho** [comment]
I receive this suggestion from log:

```
10:41:17 AM: ❯ The following Node.js modules use dynamic expressions to include files:
10:41:17 AM:    - next
10:41:17 AM:    - @ampproject/toolbox-optimizer
10:41:17 AM: ​
10:41:17 AM:   Because files included with dynamic expressions aren't bundled with your serverless functions by default,
  this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
10:41:17 AM:   modules as external in the [functions] section of your `netlify.toml` configuration file:
10:41:17 AM: ​
10:41:17 AM:   [functions]
10:41:17 AM:     external_node_modules = ["next", "@ampproject/toolbox-optimizer"]
10:41:17 AM: ​
10:41:17 AM:   Visit https://ntl.fyi/dynamic-imports for more information.
10:41:17 AM: ​
```

**Comment by lindsaylevine** [comment]
what about if you remove `next-i18next` from external_node_modules? @tgmarinho

**Comment by tgmarinho** [comment]
🚀🙏❤️🙏💻🧑‍🚀🧑‍💻🥳🎈🎉🎊🎊🎊🎉🎉🎉🎈💃💃💃🥳🥳🥳🙏

Finally, it works @lindsaylevine thank you for your support! 

```
[build]
  command = "yarn build"
  publish   = "out"

[functions]
  node_bundler = "esbuild"
	external_node_modules = ["@ampproject/toolbox-optimizer", "sharp"]
  included_files = ["public/locales/en/*.json", "/var/task/next-i18next.config.js"]
```

![KeyaanJohnWickGIF](https://user-images.githubusercontent.com/380327/131539185-24593cc5-783c-4621-a75f-495eb293620f.gif)

**Comment by lindsaylevine** [comment]
yay!!!!! let us know if you run into any other issues!

**Comment by ibqn** [comment]
I also experience this error message and have no clue at all what to do... 
 
```sh
4:09:56 PM: info  - Collecting page data...
4:10:00 PM: info  - Generating static pages (0/11)
4:10:00 PM: info  - Generating static pages (2/11)
4:10:00 PM: info  - Generating static pages (5/11)
4:10:00 PM: Unhandled error during request: Error: Cannot find module '/opt/build/repo/next-i18next.config.js'
4:10:00 PM:     at webpackEmptyContext (/opt/build/repo/.next/serverless/pages/index.js:11:10)
4:10:00 PM:     at /opt/build/repo/.next/serverless/chunks/16.js:22811:72 {
4:10:00 PM:   code: 'MODULE_NOT_FOUND'
4:10:00 PM: }
```
and this suggested configuration does not change anything 

```sh
build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/locales/en/*.json", "public/locales/de/*.json", "/var/task/next-i18next.config.js"]
```

**Comment by lindsaylevine** [comment]
@ibqn you should try the beta! https://github.com/netlify/netlify-plugin-nextjs/discussions/706
