### ISSUE TITLE
Next.js build failing due to internal error

### ISSUE THREAD

**Issue by dheeraj-murali** [netlify/netlify-plugin-nextjs#639]
**Describe the bug**
Attempts to build a nextjs projects in netlify are failing due to the error bellow.
```
Plugin "@netlify/plugin-nextjs" internal error

Error: Source and destination must not be the same.

In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
at Object.checkPathsSync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/util/stat.js:51:11)
at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
at copyPublicFiles (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/steps/copyPublicFiles.js:14:5)
at build (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:30:3)
at nextOnNetlify (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:90:11)
at onBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:123:11)
at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:20:3)
at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
at async process. (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
```

**To Reproduce**
1. Go to netlify dashboard
2. Select site
2. Go to deploys tab
3. Click Trigger deploy
4. Build fails at the stage `3. onBuild command from @netlify/plugin-nextjs ` 

**Expected behavior**
Build works without issues

**Versions**
- Next.js: 11.1.2

**Comment by dheeraj-murali** [comment]
Okay, Sorry. turns out my Publish directory got configured to a wrong destination by default. This issue is fixed
