### ISSUE TITLE
Getting error when using failback: 'blocking'

### ISSUE THREAD

**Issue by Keisuke69** [netlify/netlify-plugin-nextjs#66]
When I use `fallback: 'blocking'`, deploy failed due to an error. This error seems to be in @netlify/plugin-nextjs.
If I just set `fallback` parameter to 'false', there is no issue and deploy is successful.
This value `blocking` has been supported from Next.js 10.

Logs on the deploy log were here.

```
10:30:59 PM: ────────────────────────────────────────────────────────────────
10:30:59 PM:   Plugin "@netlify/plugin-nextjs" internal error                
10:30:59 PM: ────────────────────────────────────────────────────────────────
10:30:59 PM: ​
10:30:59 PM:   Error message
10:30:59 PM:   Error: 'netlify-automatic-functions/next_posts_id/next_posts_id.js' already exists
10:30:59 PM: ​
10:30:59 PM:   Plugin details
10:30:59 PM:   Package:        @netlify/plugin-nextjs
10:30:59 PM:   Version:        1.0.2
10:30:59 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
10:30:59 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
10:30:59 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
10:30:59 PM: ​
10:30:59 PM:   Error location
10:30:59 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
10:30:59 PM:       at mayCopyFile (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
10:30:59 PM:       at onFile (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
10:30:59 PM:       at getStats (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
10:30:59 PM:       at startCopy (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
10:30:59 PM:       at handleFilterAndCopy (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
10:30:59 PM:       at copySync (/opt/buildhome/.netlify-build-plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
10:30:59 PM:       at setupNetlifyFunctionForPage (/opt/buildhome/.netlify-build-plugins/node_modules/next-on-netlify/lib/helpers/setupNetlifyFunctionForPage.js:21:3)
10:30:59 PM:       at /opt/buildhome/.netlify-build-plugins/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:20:5
10:30:59 PM:       at Array.forEach (<anonymous>)
10:30:59 PM:       at setup (/opt/buildhome/.netlify-build-plugins/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:16:9)
```

**Comment by lindsaylevine** [comment]
hey @Keisuke69 thanks so much for opening this! i know why this is happening, unfortunately, as the current version of next-on-netlify doesn't expect a string value for fallback pages. i'm going to close this here and open a copy in github.com/netlify/next-on-netlify since that's where the issue exists. i'll tag you there!
