### ISSUE TITLE
Not working with Markdown blog

### ISSUE THREAD

**Issue by MejanH** [netlify/netlify-plugin-nextjs#71]
Hi. First of all, Thanks for the plugin. 

I am getting errors with my markdown blog. Pages and components seem to be working perfectly (tested with sample). but not working with the markdown directory. It's giving me an error related to my file location.

```json
{
"errorType": "Runtime.UnhandledPromiseRejection",
"errorMessage": "Error: ENOENT: no such file or directory, scandir '/var/task/contents/blog'",
"trace": [
"Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, scandir '/var/task/contents/blog'",
"    at process.<anonymous> (/var/runtime/index.js:35:15)",
"    at process.emit (events.js:314:20)",
"    at processPromiseRejections (internal/process/promises.js:209:33)",
"    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
]
}
```

**Comment by lindsaylevine** [comment]
hey @MejanH thanks for opening this! happy to help. however, need a little bit more info from you. the fastest/easiest way for me to help you is for you to open a repo that reproduces this issue and that i can deploy myself. from the deploy logs you shared, i don't see a markdown dir under pages which means, wherever you have it, it's excluded from what next-on-netlify or next as a framework would handle. let me know!

**Comment by MejanH** [comment]
Thanks for the reply. For the demo, I just followed the next.js learn pages. 

[The completed lesson repo](https://github.com/vercel/next-learn-starter/tree/master/typescript-final)

[Next.js Learn Page](https://nextjs.org/learn/basics/create-nextjs-app)

**Comment by lindsaylevine** [comment]
hey, i spent a bit of time trying to get `typescript-final` working on my machine. that repo seems somewhat broken. when you initially run `next dev`, you get an invalid date error. then `next build` fails trying to look for files ending in `.md.html`. because this doesn't even work locally for me, there's not much i can do.

also, i can tell from your logs in your original post that what you have deviates from `typescript-final` in at least some way. can you please open a repo with _exactly_ what you tried to deploy to netlify?

**Comment by MejanH** [comment]
Hi, I have created a repo as you said. tried with `npm run build` and `next build` as this [official post](https://www.netlify.com/blog/2020/11/30/how-to-deploy-next.js-sites-to-netlify/) says. Still the same error. It gets published successfully but not working.

[My repo](https://github.com/MejanH/nextjs-blog-incremental-static)

```
7:50:06 PM: Build ready to start
7:50:08 PM: build-image version: 53b83b6bede2920f236b25b6f5a95334320dc849
7:50:08 PM: build-image tag: v3.6.0
7:50:08 PM: buildbot version: cdcf5e6d038c4a5c0bbc618d40b7eb21a2893d7d
7:50:08 PM: Building without cache
7:50:08 PM: Starting to prepare the repo for build
7:50:08 PM: No cached dependencies found. Cloning fresh repo
7:50:08 PM: git clone https://github.com/MejanH/nextjs-blog-incremental-static
7:50:09 PM: Preparing Git Reference refs/heads/main
7:50:11 PM: Starting build script
7:50:11 PM: Installing dependencies
7:50:11 PM: Python version set to 2.7
7:50:13 PM: v12.18.0 is already installed.
7:50:13 PM: Now using node v12.18.0 (npm v6.14.4)
7:50:13 PM: Started restoring cached build plugins
7:50:13 PM: Finished restoring cached build plugins
7:50:14 PM: Attempting ruby version 2.7.1, read from environment
7:50:16 PM: Using ruby version 2.7.1
7:50:16 PM: Using PHP version 5.6
7:50:16 PM: Started restoring cached node modules
7:50:16 PM: Finished restoring cached node modules
7:50:16 PM: Installing NPM modules using NPM version 6.14.4
7:50:32 PM: > sharp@0.26.2 install /opt/build/repo/node_modules/sharp
7:50:32 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
7:50:34 PM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
7:50:37 PM: > @ampproject/toolbox-optimizer@2.7.0-alpha.1 postinstall /opt/build/repo/node_modules/@ampproject/toolbox-optimizer
7:50:37 PM: > node lib/warmup.js
7:50:38 PM: AMP OPTIMIZER Downloaded latest AMP runtime data.
7:50:38 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
7:50:38 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:50:38 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
7:50:38 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:50:38 PM: added 714 packages from 467 contributors and audited 716 packages in 20.898s
7:50:39 PM: 81 packages are looking for funding
7:50:39 PM:   run `npm fund` for details
7:50:39 PM: found 2 low severity vulnerabilities
7:50:39 PM:   run `npm audit fix` to fix them, or `npm audit` for details
7:50:39 PM: NPM modules installed
7:50:39 PM: Started restoring cached go cache
7:50:39 PM: Finished restoring cached go cache
7:50:39 PM: go version go1.14.4 linux/amd64
7:50:39 PM: go version go1.14.4 linux/amd64
7:50:39 PM: Installing missing commands
7:50:39 PM: Verify run directory
7:50:42 PM: ​
7:50:42 PM: ────────────────────────────────────────────────────────────────
7:50:42 PM:   Netlify Build                                                 
7:50:42 PM: ────────────────────────────────────────────────────────────────
7:50:42 PM: ​
7:50:42 PM: ❯ Version
7:50:42 PM:   @netlify/build 8.0.0
7:50:42 PM: ​
7:50:42 PM: ❯ Flags
7:50:42 PM:   deployId: 5fd8bf0e213e5d0054b2fb66
7:50:42 PM:   mode: buildbot
7:50:42 PM: ​
7:50:42 PM: ❯ Current directory
7:50:42 PM:   /opt/build/repo
7:50:42 PM: ​
7:50:42 PM: ❯ Config file
7:50:42 PM:   No config file was defined: using default values.
7:50:42 PM: ​
7:50:42 PM: ❯ Context
7:50:42 PM:   production
7:50:42 PM: ​
7:50:42 PM: ❯ Installing plugins
7:50:42 PM:    - @netlify/plugin-nextjs@1.0.2
7:51:21 PM: ​
7:51:21 PM: ❯ Loading plugins
7:51:21 PM:    - @netlify/plugin-nextjs@1.0.2 from Netlify app
7:51:22 PM: ​
7:51:22 PM: ────────────────────────────────────────────────────────────────
7:51:22 PM:   1. onPreBuild command from @netlify/plugin-nextjs             
7:51:22 PM: ────────────────────────────────────────────────────────────────
7:51:22 PM: ​
7:51:23 PM: ** Adding next.config.js with target set to 'serverless' **
7:51:23 PM: ​
7:51:23 PM: (@netlify/plugin-nextjs onPreBuild completed in 14ms)
7:51:23 PM: ​
7:51:23 PM: ────────────────────────────────────────────────────────────────
7:51:23 PM:   2. Build command from Netlify app                             
7:51:23 PM: ────────────────────────────────────────────────────────────────
7:51:23 PM: ​
7:51:23 PM: $ next build
7:51:24 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
7:51:24 PM: info  - Creating an optimized production build...
7:51:43 PM: warn  - Compiled with warnings
7:51:43 PM: ./node_modules/next/dist/next-server/server/load-components.js
7:51:43 PM: Critical dependency: the request of a dependency is an expression
7:51:43 PM: ./node_modules/next/dist/next-server/server/load-components.js
7:51:43 PM: Critical dependency: the request of a dependency is an expression
7:51:43 PM: ./node_modules/next/dist/next-server/server/require.js
7:51:43 PM: Critical dependency: the request of a dependency is an expression
7:51:43 PM: ./node_modules/next/dist/next-server/server/require.js
7:51:43 PM: Critical dependency: the request of a dependency is an expression
7:51:43 PM: ./node_modules/next/dist/next-server/server/require.js
7:51:43 PM: Critical dependency: the request of a dependency is an expression
7:51:43 PM: ./node_modules/node-fetch/lib/index.js
7:51:43 PM: Module not found: Can't resolve 'encoding' in '/opt/build/repo/node_modules/node-fetch/lib'
7:51:43 PM: info  - Collecting page data...
7:51:44 PM: info  - Generating static pages (0/5)
7:51:45 PM: info  - Generating static pages (1/5)
7:51:45 PM: info  - Generating static pages (2/5)
7:51:45 PM: info  - Generating static pages (3/5)
7:51:45 PM: info  - Generating static pages (5/5)
7:51:45 PM: info  - Finalizing page optimization...
7:51:46 PM: Page                              Size     First Load JS
7:51:46 PM: ┌ ● / (ISR: 1 Seconds)            631 B          71.3 kB
7:51:46 PM: ├   /_app                         0 B            60.2 kB
7:51:46 PM: ├ ○ /404                          2.75 kB        62.9 kB
7:51:46 PM: ├ λ /api/hello                    0 B            60.2 kB
7:51:46 PM: └ ● /posts/[id]                   433 B          71.1 kB
7:51:46 PM:     ├ /posts/pre-rendering
7:51:46 PM:     ├ /posts/ssg-ssr
7:51:46 PM:     └ /posts/testing-ssg
7:51:46 PM: + First Load JS shared by all     60.2 kB
7:51:46 PM:   ├ chunks/commons.87066d.js      13 kB
7:51:46 PM:   ├ chunks/framework.9ec1f7.js    39.9 kB
7:51:46 PM:   ├ chunks/main.bb7417.js         6.22 kB
7:51:46 PM:   ├ chunks/pages/_app.ec7c07.js   296 B
7:51:46 PM:   ├ chunks/webpack.e06743.js      751 B
7:51:46 PM:   └ css/2fd5d76e8788e1d11cbb.css  264 B
7:51:46 PM: λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
7:51:46 PM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
7:51:46 PM: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
7:51:46 PM:    (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
7:51:46 PM: ​
7:51:46 PM: (build.command completed in 23.1s)
7:51:46 PM: ​
7:51:46 PM: ────────────────────────────────────────────────────────────────
7:51:46 PM:   3. onBuild command from @netlify/plugin-nextjs                
7:51:46 PM: ────────────────────────────────────────────────────────────────
7:51:46 PM: ​
7:51:46 PM: ** Running Next on Netlify package **
7:51:46 PM: 🚀 Next on Netlify 🚀
7:51:46 PM:    Functions directory:  netlify-automatic-functions
7:51:46 PM:    Publish directory:  /opt/build/repo
7:51:46 PM:    Make sure these are set in your netlify.toml file.
7:51:46 PM: 🌍️ Copying public/ folder to /opt/build/repo
7:51:46 PM: 💼 Copying static NextJS assets to /opt/build/repo
7:51:46 PM: 💫 Setting up API endpoints as Netlify Functions in netlify-automatic-functions
7:51:46 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in netlify-automatic-functions
7:51:46 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in netlify-automatic-functions
7:51:46 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo
7:51:46 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in netlify-automatic-functions
7:51:46 PM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in netlify-automatic-functions
7:51:46 PM: 🔥 Copying pre-rendered pages without props to /opt/build/repo
7:51:46 PM: 🔀 Setting up redirects
7:51:46 PM: ​
7:51:46 PM: (@netlify/plugin-nextjs onBuild completed in 127ms)
7:51:46 PM: ​
7:51:46 PM: ────────────────────────────────────────────────────────────────
7:51:46 PM:   4. Functions bundling                                         
7:51:46 PM: ────────────────────────────────────────────────────────────────
7:51:46 PM: ​
7:51:46 PM: Packaging Functions from netlify-automatic-functions directory:
7:51:46 PM:  - next_api_hello/next_api_hello.js
7:51:46 PM:  - next_index/next_index.js
7:51:46 PM:  - next_posts_id/next_posts_id.js
7:52:00 PM: ​
7:52:00 PM: (Functions bundling completed in 14.3s)
7:52:00 PM: ​
7:52:00 PM: ────────────────────────────────────────────────────────────────
7:52:00 PM:   Netlify Build Complete                                        
7:52:00 PM: ────────────────────────────────────────────────────────────────
7:52:00 PM: ​
7:52:00 PM: (Netlify Build completed in 1m 18.6s)
7:52:01 PM: Caching artifacts
7:52:01 PM: Started saving node modules
7:52:01 PM: Finished saving node modules
7:52:01 PM: Started saving build plugins
7:52:01 PM: Finished saving build plugins
7:52:01 PM: Started saving pip cache
7:52:01 PM: Finished saving pip cache
7:52:01 PM: Started saving emacs cask dependencies
7:52:01 PM: Finished saving emacs cask dependencies
7:52:01 PM: Started saving maven dependencies
7:52:01 PM: Finished saving maven dependencies
7:52:01 PM: Started saving boot dependencies
7:52:01 PM: Finished saving boot dependencies
7:52:01 PM: Started saving rust rustup cache
7:52:01 PM: Finished saving rust rustup cache
7:52:01 PM: Started saving rust cargo bin cache
7:52:01 PM: Finished saving rust cargo bin cache
7:52:01 PM: Started saving go dependencies
7:52:01 PM: Finished saving go dependencies
7:52:04 PM: Build script success
7:52:04 PM: Starting to deploy site from ''
7:52:04 PM: Creating deploy tree 
7:52:04 PM: Creating deploy upload records
7:52:05 PM: 5 new files to upload
7:52:05 PM: 3 new functions to upload
7:52:06 PM: Starting post processing
7:52:06 PM: Post processing - HTML
7:52:07 PM: Post processing - header rules
7:52:07 PM: Post processing - redirect rules
7:52:07 PM: Post processing done
7:52:07 PM: Site is live ✨
7:52:28 PM: Finished processing build request in 2m19.653681844s
```

### JSON error after publishing

```
{
"errorType": "Runtime.UnhandledPromiseRejection",
"errorMessage": "Error: ENOENT: no such file or directory, scandir '/var/task/posts'",
"trace": [
"Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, scandir '/var/task/posts'",
"    at process.<anonymous> (/var/runtime/index.js:35:15)",
"    at process.emit (events.js:314:20)",
"    at processPromiseRejections (internal/process/promises.js:209:33)",
"    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
]
}
```

**Comment by lindsaylevine** [comment]
@MejanH ok WEW finally got this deployed and diagnosed! so here's what's going on:

because these pages are trying to use ISR (see `revalidate` flag in your `getStaticProps` functions), our plugin turns these pages into netlify functions. from within the function['s node env], the files (aka the markdown) you're trying to read "from disk" are not bundled with those functions, so it's failing to find them and erroring out.

this is something we can/should address, but for now, if you want this to Just Work, don't use ISR/revalidate. it will work as a plain SSG'd/prerendered page.

thanks for opening that separate repo for me and let me know if you have any other questions!! i'm going to change the title if that's cool to be a little more specific to the issue :)

**Comment by MejanH** [comment]
Thanks for the help. Will wait for this feature.
