### ISSUE TITLE
[Bug]: Plugin "@netlify/plugin-nextjs" internal error 

### ISSUE THREAD

**Issue by eric-stanley** [netlify/netlify-plugin-nextjs#714]
### Steps to reproduce

When deploying a nextjs app, I am getting the below error

`Plugin "@netlify/plugin-nextjs" internal error`

`Error: Source and destination must not be the same.
In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
at Object.checkPathsSync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/util/stat.js:51:11)
at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
at copyPublicFiles (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/steps/copyPublicFiles.js:14:5)
at build (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:30:3)
at nextOnNetlify (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:90:11)
at onBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:123:11)
at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.22.6/lib/node_modules/@netlify/build/src/plugins/child/run.js:20:3)
at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.22.6/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
at async process. (/opt/buildhome/.netlify-build-nvm/versions/node/v12.22.6/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)`

Tried to change the `target` in `next.config.js` file to `serverless` and got another error (`Error: Cannot find module ‘./next-i18next.config.js’`)
![netlify_plugin_error](https://user-images.githubusercontent.com/4955170/137595207-0856ef60-137f-4d56-9c3b-cc8d253602fa.png)

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Linux

**Comment by lindsaylevine** [comment]
@eric-stanley hey eric! we JUST released the beta of our full plugin rewrite. i think it could resolve your issue. would you be open to testing it out? instructions inside our discussion here: https://github.com/netlify/netlify-plugin-nextjs/discussions/706. let us know! 🙏

**Comment by seanmodd** [comment]
I'm having a very similar problem to eric @lindsaylevine I'd be very interested in testing out the beta!!!

**Comment by lindsaylevine** [comment]
@seanmodd this usually means some file in your /public dir happens to also exist in your netlify publish dir. feel free to test the beta by checking out the discussion #706!

**Comment by ascorbic** [comment]
Closing because this is fixed in the beta
