### ISSUE TITLE
[Bug]: Issues with custom CI 

### ISSUE THREAD

**Issue by iamchathu** [netlify/netlify-plugin-nextjs#754]
### Steps to reproduce

We are using GitLab CI to build and deploy Next.js application to Netlify.

We are using `netlify-cli` and deploy and has ` "@netlify/plugin-nextjs": "^4.0.0-beta.4"`

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Linux

### Your `netlify.toml` file

```shell
[build]
command = "yarn build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

```

### Relevant log output (or link to your logs)

1:42:21 PM 3c34ddf9 ERROR  /var/task/packages/buddhi-batiks/.next/server/chunks/9.js:34
        pollingInterval: parseInt(process.env.NEXT_PUBLIC_POLLING_INTERVAL ?? '180000', 10)
                                                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/var/task/packages/buddhi-batiks/.next/server/webpack-runtime.js:143:28)
    at /var/task/packages/buddhi-batiks/.next/server/webpack-runtime.js:70:40
    at Array.reduce (<anonymous>)
1:42:21 PM 3c34ddf9 ERROR  /var/task/packages/buddhi-batiks/.next/server/chunks/9.js:34
        pollingInterval: parseInt(process.env.NEXT_PUBLIC_POLLING_INTERVAL ?? '180000', 10)
                                                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/var/task/packages/buddhi-batiks/.next/server/webpack-runtime.js:143:28)
    at /var/task/packages/buddhi-batiks/.next/server/webpack-runtime.js:70:40
    at Array.reduce (<anonymous>)
1:42:21 PM 3c34ddf9 Duration: 44.54 ms	Memory Usage: 75 MB	Init Duration: 451.76 ms

Before moving to beta we deployed out directory and worked without issues.

**Comment by ascorbic** [comment]
Hi. In the dashboard of your site, can you set the env var `AWS_LAMBDA_JS_RUNTIME` to `nodejs14.x`. It needs to be in the UI, not in the toml or a .env file. You can also set it locally from the cli by running `netlify env:set AWS_LAMBDA_JS_RUNTIME nodejs14.x`
