### ISSUE TITLE
[Bug]: Build fails with "chunk already exists" error

### ISSUE THREAD

**Issue by rudietuesdays** [netlify/netlify-plugin-nextjs#764]
### Steps to reproduce

Hi! My team has been using Netlify to build a Next site and it's been working great until we've hit a snag today. We transferred the repo to a different owner a few hours ago. We were able to reconnect it just fine, but haven't been able to build since switching to the new repo. Now on build, every time we get an `internal error`.

Here's the full error:
```
Plugin "@netlify/plugin-nextjs" internal error

Error: '/opt/build/repo/out/_next/static/chunks/126-d7ef31942f62e0a9.js' already exists

In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
at mayCopyFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
at onFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
at getStats (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
at startCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
at copyDirItem (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:122:10)
at /opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:39
at Array.forEach ()
at copyDir (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:23)
at onDir (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:105:10)
at getStats (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
```

I've noticed some folks have had similar issues but I haven't seen a fix that works for my error with the chunks already existing. Any help would be greatly appreciated. Thanks!

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

### Your `netlify.toml` file

```shell
N/A
```

**Comment by ascorbic** [comment]
Hi @rudietuesdays 
Could you try clearing the cache and rebuilding? Failing that, could you try the new beta plugin. See the readme for instructions.

**Comment by rudietuesdays** [comment]
Hi @ascorbic , I had tried clearing the cache and rebuilding and it didn't work. I also tried upgrading to the beta, which also failed but gave a better error message and I was able to fix it from there. Thanks!

**Comment by ascorbic** [comment]
Oh great! What was the problem in the end?

**Comment by rudietuesdays** [comment]
It seemed to be because we were running `next build && next export`. Once we removed the export command, it ran successfully.

**Comment by ascorbic** [comment]
Ah, yes that would explain it. The plugin does not support sites that use `next export`
